const fs = require('node:fs');
const path = require('node:path');
const { keywordRoutes, canonicalPath } = require('./keyword-model.cjs');
const root = path.resolve(__dirname, '..');
const defaultGlobals = keywordRoutes().filter(route => route.length === 1).map(route => route[0]);
const rootPairs = require('../src/node-types.json').filter(node => node.type.startsWith('_ci_root'))
  .flatMap(node => node.subtypes.filter(subtype => ['block_mapping_pair', 'flow_pair'].includes(subtype.type))
    .map(subtype => `${node.type}/${subtype.type}`));
if (!rootPairs.length) throw new Error('Missing root-pair metadata; run mise run generate');
const escapeRegex = value => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const keyRegex = keys => `^["']?(${keys.map(escapeRegex).join('|')})["']?$`;
const match = (capture, keys, negative = false) =>
  `(#${negative ? 'not-match?' : 'match?'} @${capture} ${JSON.stringify(keyRegex(keys))})`;
const mapping = pair => `(_ (_ ${pair}))`;
const sequence = (value, pair) => {
  // YAML permits an implicit one-pair mapping in a flow sequence: [if: $A].
  return `(_ [(block_sequence (block_sequence_item ${value})) (flow_sequence ${pair ? `[${value} ${pair}]` : value})])`;
};

// Hidden supertypes identify document-level pairs without scanning the whole
// document for a viewport query. Keep the concrete subtype so Tree-sitter can
// index patterns by node type. The rest of each path retains its YAML context.
function atPath(route, value, leafCapture, globals = defaultGlobals, capturePair = false) {
  const predicates = [];
  let node = value;
  let pair;
  for (let index = route.length - 1; index >= 0; index--) {
    const key = route[index];
    if (key === '[]') {
      node = sequence(node, pair);
      pair = undefined;
      continue;
    }
    const capture = index === route.length - 1 && leafCapture ? leafCapture : `_path${index}`;
    const keyNode = `(flow_node) @${capture}`;
    if (key === '*') {
      if (index === 0) predicates.push(match(capture, globals, true));
    } else predicates.push(match(capture, Array.isArray(key) ? key : [key]));
    pair = `(_ key: ${keyNode}${node ? ` value: ${node}` : ''})`;
    if (capturePair && index === route.length - 1) pair += ' @injection.content';
    node = index === 0 ? `[${rootPairs.map(type => pair.replace('(_ key:', `(${type} key:`)).join('\n')}]` : mapping(pair);
  }
  return { node, predicates };
}

function outputs(reference = require('../data/keyword-schema.json'), predefined = require('../data/predefined-variables.json')) {
  if (predefined.revision !== reference.revision || !predefined.names.length ||
      predefined.names.some(name => !/^[A-Z][A-Z0-9_]*$/.test(name))) {
    throw new Error('Expected predefined variable names from the same GitLab revision; run mise run reference:sync');
  }
  const routes = keywordRoutes(reference.schema);
  const globals = routes.filter(route => route.length === 1).map(route => route[0]);
  function pattern(route, value, capture, directives = [], capturePair = false) {
    const { node, predicates } = atPath(route, value, capture, globals, capturePair);
    return `(${node}\n  ${[...predicates, ...directives].join('\n  ')})\n`;
  }
  const groups = new Map();
  for (const route of routes) {
    const parent = route.slice(0, -1);
    const key = JSON.stringify(parent);
    if (!groups.has(key)) groups.set(key, { parent, keys: [] });
    groups.get(key).keys.push(route.at(-1));
  }
  let highlights = fs.readFileSync(path.join(root, 'data/yaml-highlights.scm'), 'utf8');
  highlights += '\n; Generated by scripts/generate-queries.cjs. Edit data/keyword-schema.json via reference:sync.\n';
  // Structural captures overlap YAML scalars. Explicit precedence keeps their
  // colors stable when hosts query different visible ranges of the document.
  const priority = ['(#set! priority 110)'];
  highlights += pattern(['*'], null, 'function', priority);
  for (const { parent, keys } of groups.values()) {
    highlights += `\n; ${[...parent, `{${keys.join(', ')}}`].join(':')}\n`;
    highlights += pattern([...parent, keys], null, 'keyword', priority);
  }
  highlights += '\n((tag) @keyword (#eq? @keyword "!reference") (#set! priority 110))\n';
  highlights += '\n' + fs.readFileSync(path.join(root, 'data/expression-highlights.scm'), 'utf8');
  highlights += '\n; Generated from data/predefined-variables.json via reference:sync.\n';
  highlights += `((variable) @variable.builtin\n  (#any-of? @variable.builtin\n${predefined.names.map(name => `    "$${name}" "\${${name}}"`).join('\n')})\n  (#set! priority 111))\n`;

  let injections = `; Generated by scripts/generate-queries.cjs.
; Configuration expressions may occur in scalar keys or values.
([(string_scalar) (single_quote_scalar) (double_quote_scalar) (block_scalar)] @injection.content
 (#match? @injection.content "\\\\$\\\\[\\\\[")
 (#set! injection.language "gitlab_ci")
 (#set! gitlab_ci.kind "template")
 (#set! injection.include-children))
`;
  // Ten nested block sequences add thirty wrappers around a scalar. Matching
  // wrapper depths also covers flow and mixed sequence styles.
  const scriptScalars = ['string_scalar', 'single_quote_scalar', 'double_quote_scalar', 'block_scalar']
    .map(type => `(${type}) @injection.content`).join(' ');
  let scriptValue = `[${scriptScalars}]`;
  for (let depth = 0; depth < 31; depth++) scriptValue = `[${scriptScalars} (_ ${scriptValue})]`;
  scriptValue = `(_ ${scriptValue})`;
  for (const route of routes.filter(route => ['script', 'before_script', 'after_script'].includes(route.at(-1)))) {
    injections += `\n; Variable references in ${canonicalPath(route)}.\n` + pattern(route, scriptValue, null, [
      '(#match? @injection.content "\\\\$[A-Za-z_{]")',
      '(#not-match? @injection.content "\\\\$\\\\[\\\\[")',
      '(#set! injection.language "gitlab_ci")', '(#set! gitlab_ci.kind "template")', '(#set! injection.include-children)',
    ]);
  }
  const scalar = `(_ [(plain_scalar (string_scalar))
    (single_quote_scalar) (double_quote_scalar) (block_scalar)])`;
  const directives = ['(#set! injection.language "gitlab_ci")', '(#set! gitlab_ci.kind "condition")', '(#set! injection.include-children)'];
  for (const route of routes.filter(route => route.at(-1) === 'if' && route.includes('rules'))) {
    injections += `\n; ${canonicalPath(route)}\n` + pattern(route, scalar, null, directives, true);
  }
  for (const filter of ['only', 'except']) {
    injections += `\n; Deprecated ${filter}:variables conditions.\n` +
      pattern(['*', filter, 'variables'], '(_ [(block_sequence) (flow_sequence)])', null,
        ['(#set! injection.language "gitlab_ci")', '(#set! gitlab_ci.kind "conditions")', '(#set! injection.include-children)'], true);
  }
  const inventory = {
    revision: reference.revision,
    globalKeywords: globals,
    jobKeywords: routes.filter(route => route.length === 2 && route[0] === '*').map(route => route[1]),
    paths: [...new Set(routes.map(canonicalPath))].sort(),
    routes,
  };
  return {
    'queries/highlights.scm': highlights,
    'queries/injections.scm': injections,
    'data/keyword-inventory.json': JSON.stringify(inventory, null, 2) + '\n',
  };
}

if (require.main === module) {
  const check = process.argv.includes('--check');
  for (const [file, content] of Object.entries(outputs())) {
    if (check) {
      if (fs.readFileSync(path.join(root, file), 'utf8') !== content) throw new Error(`Stale ${file}; run mise run generate`);
    } else fs.writeFileSync(path.join(root, file), content);
  }
  console.log(`${check ? 'Checked' : 'Generated'} ${keywordRoutes().length} contextual keyword routes`);
}

module.exports = { outputs, atPath };
